### ISSUE TITLE
Ownership privileges required for repo

### ISSUE THREAD

**Issue by axunonb** [axuno/SmartFormat.NET#110]
@scottrippey 
Hi Scott,
It's been almost 2 years now since I took over maintaining the repo you initially invented. 
Now I'd like to work with webhooks for codecov and appveyor, which requires ownership privileges in order to administrate. Would you consider [transferring ownership](https://help.github.com/articles/about-repository-transfers/) to me (available menu item in the settings of the repo)?
An alternative would be forking, but then repo would exist twice and all existing links would still point to the existing one.
What do you think?
If you prefer, leave a message using our [web site contact form](https://www.axuno.net/contact/message).
Norbert

**Comment by scottrippey** [comment]
Norbert, You've done an amazing job of maintaining this project! I'd be more-than-happy to hand it over!
Codecov and AppVeyor are awesome, I've been using them for other projects and I've often wished for CI integration for this project too.  But I really don't spend time in the .NET world anymore, and although I do feel passionate about this project, I just don't know the tools well enough to keep this relevant.  So I will initiate the transfer.  Thanks for doing a great job here!

**Comment by scottrippey** [comment]
Transfer complete!
How about NuGet?  Need anything from me to transfer the NuGet ownership?

**Comment by axunonb** [comment]
Hi Scott, very good, thank you. Nothing to do with NuGet I think. There are 3 owners, and that's fine.
Actually I feel sorry for your priorities changing, while at same time this happens and happened in my case as well. Again, thanks a lot for initiating this great library. I would still be happy if I could approach you for questions from time to time. Let's keep in touch.
One question is already there:
When you built the parser, have you been creating a [Backus-Naur Form](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) definition for the grammar? It's not included in the repo, but would be helpful. Better ask than re-engineer ;-)
