### ISSUE TITLE
DateTime -> Different Timezone possible

### ISSUE THREAD

**Issue by jogibear9988** [axuno/SmartFormat.NET#111]
In my Backend I store every DateTime as UTC, but I use SmartFormat for sending Messages to my customer. Is it possible to change the TimeZone of the DateTime via SmartFormat?

**Comment by axunonb** [comment]
Hi Jochen, that's a good point. The [```TimeFormatter```](https://github.com/axuno/SmartFormat.NET/blob/master/src/SmartFormat/Extensions/TimeFormatter.cs) works with the ```DateTime``` structure, so it's not aware of time zones. So we could think about a setting for the formatter to either work with ```DateTime``` or [```DateTimeOffset```](https://msdn.microsoft.com/en-us/library/system.datetimeoffset(v=vs.110).aspx). It would be great if you posted a PR for that.
