### ISSUE TITLE
call method if passed

### ISSUE THREAD

**Issue by ctrl-d** [axuno/SmartFormat.NET#114]
I want to give users option to render some things that may need to load from database or other method,
rather then running all methods & passing objects with values, Is it possible to just pass in method & it should only get called if its needed in template

**Comment by axunonb** [comment]
Yes, you can by writing your own formatter which fits to your needs. I wouldn't recommend to load data from a database inside a formatter for performance reasons. Rather load the data and pass them to Smart.Format as parameters.

**Comment by ctrl-d** [comment]
Yes I was looking into formatters
Looks like it will do exactly what I need
I know that it's not the best practice to do that
But from the other side I have some functions that I want to call only if the user wants it
And most users we'll never need them

So I don't want to call the database for all requests because just a few percent of users will want some additional information

But I got my answer thank you so much
