### ISSUE TITLE
Support for UTC dates

### ISSUE THREAD

**Issue by kazfernandes** [axuno/SmartFormat.NET#115]
It would be great to see support for UTC dates in SmartFormat.NET. This is similar to issue #111 but easier to implement, and these days many applications are utilising UTC dates for consistency.

From what I can see, the following changes would be needed:

- adding a new configuration option for UseUtcDates (default=false for backwards compatibility)
- change line 103 in Extensions\ConditionalFormatter.cs:
if (paramCount == 3 && arg.Date == USE_UTC_DATES ? DateTime.UtcNow.Date : DateTime.Today)
- change line 105 in Extensions\ConditionalFormatter.cs:
else if (arg <= USE_UTC_DATES ? DateTime.UtcNow : DateTime.Now)
- change lines 63, 68 (both are the same) in Extensions\TimeFormatter.cs:
fromTime = (USE_UTC_DATES ? DateTime.UtcNow : DateTime.Now).Subtract((DateTime) current);
- update code for demo and tests if required

**Comment by axunonb** [comment]
Kaz, I gave this some thoughts. I agree, it would be great to have support for UTC dates. Talking about **DateTime**, it has a ```Kind``` property, which can be ```Kind.Utc```, ```Kind.Local``` and ```Kind.Unspecified```. Though the proposal looks simple to implement, my concerns come from ```Kind.Unspecified``` after reading some publications, where the best one was [this article](https://blog.nodatime.org/2011/08/what-wrong-with-datetime-anyway.html). The proposal https://github.com/axuno/SmartFormat.NET/issues/111, to introduce ```DateTimeOffset``` could be easier to use because of less ambiguities. What do you think? Could I count on your support for discussions and testing?

**Comment by kazfernandes** [comment]
Hi Norbert, thanks for getting back to me. I've read up extensively on the limitations (and workarounds) for DateTime vs. using DateTimeOffset recently. I realise that adding support for DateTimeOffset would be valuable for other developers using SmartFormat.NET. But for our project (and probably many others too), using DateTime (with UTC dates throughout the application) is a much better fit than moving to DateTimeOffset.

Perhaps you could add support for UTC dates now (quick to add, useful to many devs/projects, would definitely be used in our application), and then look at adding DateTimeOffset at a later point?

**Comment by axunonb** [comment]
Should be resolved with [Release 2.4.0.0](https://github.com/axuno/SmartFormat.NET/releases/tag/v2.4.0.0), which adds support for ```DateTimeOffset```. I think it was worth the effort to avoid the ```DateTime``` workaround, Let me know whether this works for you, please.

**Comment by kazfernandes** [comment]
Thanks Norbert, I'm sure this will be useful to many other application developers. As I mentioned previously, our application uses DateTime with the DateTimeKind set to Utc - so adding support for DateTimeOffset isn't of any use to us unfortunately.

**Comment by axunonb** [comment]
Indeed, that's understandable in your case. On the other hand I couldn't figure out a clean and generally working design which includes "mixed comparisons" including ```Kind.Unspecified```. I assume, this is why finally ```DateTimeOffset``` was introduced to the framework.
If you still find SmartFormat.Net useful, it's easy to integrate custom formatters or replace existing ones:
E.g. ```var sf = Smart.CreateDefaultSmartFormat()``` and then remove or add ```sf.FormatterExtensions``` as required. No need to work with a custom repo.

**Comment by axunonb** [comment]
Well, probably I was too close to the proposal about a new setting ```UseUtcDates```, which actually is unnecessary. Comparisons can **always** use the ```.ToUniversalTime()``` representation for ```DateTimeKind.Local``` or ```DateTimeKind.Utc```.

Comparing ```DateTimeKind.Local``` and ```DateTimeKind.Utc``` to ```DateTimeKind.Unspecified``` has always been ambigous: it represents the local time in some unspecified time zone. When ```.ToUniversalTime()``` is called, it converts from the current system's time zone. But when ```.ToLocalTime()``` is called, the "unspecified" value is taken as Universal Time.

This being said, I decided to always convert ```.ToUniversalTime()``` and published the new 
[Release 2.4.1](https://github.com/axuno/SmartFormat.NET/releases/tag/v2.4.1.0)

**Comment by kazfernandes** [comment]
Thanks for the update.

.ToUniversalTime() can cause a problem when used with DateTimeKind.Local due to daylight saving. I'd recommend using DateTime.SpecifyKind as a more consistent way to convert dates to UTC:

DateTime utcDate = DateTime.SpecifyKind(anyDate, DateTimeKind.Utc);

**Comment by axunonb** [comment]
Hi again, Kaz.
If ```anyDate``` (as the name implies) may also be set to ```DateTimeKind.Local```, do I understand your remark correctly:
```
var anyDate = new DateTime(2019,01, 01, 12, 00, 00, DateTimeKind.Local);
var utcDate = DateTime.SpecifyKind(anyDate, DateTimeKind.Utc);
if (anyDate.Ticks == utcDate.Ticks && anyDate.ToUniversalTime() != utcDate.ToUniversalTime())
{
    // this is another instant:
    Console.WriteLine($"{nameof(utcDate)} has former local time value now interpreted as UTC");
}
```
With the current implementation, the conversion with ```.ToUniversalTime()``` will do no conversion for ```DateTimeKind.Utc``` according to the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.touniversaltime?view=netframework-4.7.2#System_DateTime_ToUniversalTime), whereas with Local or Unspecified the library will behave like the .Net Framework. I assume this is what could be expected? 
In your environment, where all dates are UTC, ```.ToUniversalTime()``` does not harm anyway.
